#!/usr/bin/perl -w
#
# Copyright (C) 201 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use esmith::Build::CreateLinks  qw(:all);

#--------------------------------------------------
# Event nethserver-mattermost-update 
#--------------------------------------------------

$event = 'nethserver-mattermost-update';

event_actions($event, qw(
  initialize-default-databases 00
  nethserver-mattermost-conf 20
  nethserver-mattermost-conf-json 30
));

event_templates($event, qw(
  /etc/httpd/conf.d/zz_mattermost.conf
));

event_services($event, qw(
  httpd restart
  mattermost restart
));

#--------------------------------------------------
# Event nethserver-mattermost-save
#--------------------------------------------------

$event = 'nethserver-mattermost-save';

event_templates($event, qw(
  /etc/httpd/conf.d/zz_mattermost.conf
));

event_services($event, qw(
  httpd restart
  mattermost restart
));


#--------------------------------------------------
# actions for pre-backup-data event
#--------------------------------------------------

$event = 'pre-backup-data';

event_actions($event, 'nethserver-mattermost-backup' => 50);

#--------------------------------------------------
# actions for post-restore-data event
#--------------------------------------------------

$event = 'post-restore-data';

event_actions($event, 'nethserver-mattermost-restore' => 50);

event_services($event, 'httpd' => 'restart');
event_services($event, 'mattermost' => 'restart');

#--------------------------------------------------
# actions for tls-policy-save event
#--------------------------------------------------

$event = 'tls-policy-save';

event_templates($event, qw(
  /etc/httpd/conf.d/zz_mattermost.conf
));

