#!/bin/bash

tarball=nethserver-mattermost.tar.gz
bdir=$(mktemp -d -p .)
trap "rm -rf ${bdir}" EXIT

cp -a ui/* ${bdir}
gzip ${bdir}/i18n/language.json
tar -C ${bdir} -c -z -f ${tarball} . && echo "[INFO] created ${tarball}"