#!/usr/bin/perl

#
# Copyright (C) 2017 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use JSON;
use NethServer::Password;
my $config = "/opt/mattermost/config/config.json";
my $password = NethServer::Password::store('mattermost');


my $json;
{
  local $/;
  open my $fh, "<", $config;
  $json = <$fh>;
  close $fh;
}
my $data = decode_json($json);

print $data->{'DataSource'}."\n";
$data->{'SqlSettings'}->{'DriverName'} = "postgres";
$data->{'SqlSettings'}->{'DataSource'} = "postgres://mattuser:$password\@localhost:55432/mattermost?sslmode=disable&connect_timeout=10";

$data->{'FileSettings'}->{'Directory'} = "/var/lib/nethserver/mattermost/data";

open my $fh, ">", $config;
print $fh encode_json($data);
close $fh;

my $uid = getpwnam 'mattermost';
my $gid = getgrnam 'mattermost';

chown $uid, $gid, $config;
